// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_PinjamRuang_backend.Data;

#nullable disable

namespace _2026_PinjamRuang_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209060217_AddDataSeeding")]
    partial class AddDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2026_PinjamRuang_backend.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalPeminjaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Peminjamans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 13, 2, 16, 886, DateTimeKind.Local).AddTicks(5946),
                            Keperluan = "Gladi Bersih Wisuda",
                            NamaPeminjam = "Admin Kampus",
                            Ruangan = "Aula Utama",
                            Status = "Approved",
                            TanggalPeminjaman = new DateTime(2026, 2, 11, 13, 2, 16, 886, DateTimeKind.Local).AddTicks(5927)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 9, 13, 2, 16, 886, DateTimeKind.Local).AddTicks(5952),
                            Keperluan = "Kunjungan Industri",
                            NamaPeminjam = "Mahasiswa Tamu",
                            Ruangan = "Lab Komputer 1",
                            Status = "Pending",
                            TanggalPeminjaman = new DateTime(2026, 2, 14, 13, 2, 16, 886, DateTimeKind.Local).AddTicks(5950)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
