// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_PinjamRuang_backend.Data;

#nullable disable

namespace _2026_PinjamRuang_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2026_PinjamRuang_backend.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalPeminjaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Peminjamans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 7, 10, 55, 7, 581, DateTimeKind.Utc).AddTicks(430),
                            Keperluan = "Seminar Proposal",
                            NamaPeminjam = "Nabila",
                            Ruangan = "Aula Utama",
                            Status = "Approved",
                            TanggalPeminjaman = new DateTime(2026, 2, 8, 17, 55, 7, 581, DateTimeKind.Local).AddTicks(436)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 7, 10, 55, 7, 581, DateTimeKind.Utc).AddTicks(451),
                            Keperluan = "Praktikum Tambahan",
                            NamaPeminjam = "Budi Santoso",
                            Ruangan = "Lab Komputer 1",
                            Status = "Pending",
                            TanggalPeminjaman = new DateTime(2026, 2, 10, 17, 55, 7, 581, DateTimeKind.Local).AddTicks(452)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
